version: '3'
services:
  mysql:
    container_name: some_mysql
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306

  app:
    container_name: simple-spring-examples
    image: simple-spring-examples
    ports:
      - 8080:8080
    depends_on:
      - mysql