version: '3'
services:
  mysql:
    environment:
    - MYSQL_DATABASE=examples
    - MYSQL_PASSWORD=examples
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=examples
    image: mysql:latest
    ports:
    - 3306:3306

  myapp:
    image: simple-spring-examples:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/examples