DROP TABLE IF EXISTS book;
CREATE TABLE book (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SHORT_DESCRIPTION VARCHAR(500),
    PRIMARY KEY (ID)
);

INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Catcher in the Rye', 'A book about Holden.');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('The Firm', 'A book about Lawyers.');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 1', 'TB1');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 2', 'TB2');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 3', 'TB3');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 4', 'TB4');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 5', 'TB5');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 6', 'TB6');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 7', 'TB7');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 8', 'TB8');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 9', 'TB9');
INSERT INTO book (NAME, SHORT_DESCRIPTION) VALUES ('Test Book 10', 'TB10');