spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/examples
    username: testdb
    password: testdb
    test-on-borrow: true
    validation-query: "SELECT 1"
management:
  security:
    enabled: false
