---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-java
    tag: '8'

inputs:
- name: concourse-pipeline-samples
- name: current-app-info

run:
  path: concourse-pipeline-samples/ci/tasks/load-tests
