---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-java
    tag: "8"

inputs:
- name: simple-spring-examples
- name: current-app-info

run:
  path: simple-spring-examples/ci/tasks/update-routes
