mysql-options: '?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_HOST}:3306/test${mysql-options}
    username: psheldon
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
