groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - promote-new-version

resources:
- name: simple-spring-examples
  type: git
  source:
    branch: concourse-pipeline
    uri: http://github.com/pksheldon4/simple-spring-examples.git
- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: simple-spring-examples
    trigger: true
  - task: run-unit-tests
    file: simple-spring-examples/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: simple-spring-examples
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: simple-spring-examples/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: prepare-app-manifest
    file: simple-spring-examples/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
  - task: build-and-package
    file: simple-spring-examples/ci/tasks/build-and-package.yml
  - put: PWS
    params:
      manifest: app-manifest-output/manifest.yml
      path: target/simple-spring-examples-*.jar

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: simple-spring-examples
    trigger: true
    passed:
      - deploy-app
      # - load-tests
  - task: get-current-app-color
    file: simple-spring-examples/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: switch-app-routes
    file: simple-spring-examples/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_DOMAIN: {{pws-app-domain}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
